### PR TITLE
Some fixes/changes to the documentation

### LINKED ISSUE #86: README: Update the reference documents section
_Originally posted by @DougManuel in https://github.com/Big-Life-Lab/PHES-ODM-Validation/pull/53#pullrequestreview-1210211533_

### PR DESCRIPTION
**Pull request by yulric**
Fixes #86, #85, #77, and #84

* All the changes to the qmd/md files involves the angle brackets issue
* Had to change the h1 font-size in Shane's CSS to 40px so that the logo text did not take up 3 lines

### CODE REVIEW

**Review by DougManuel — APPROVED** [review]
Looks good. No comments.

**Review by zargot — CHANGES_REQUESTED** [review]
can we remove the authors section, or just use OHRI as the author?

**Comment by DougManuel** [comment]
> can we remove the authors section, or just use OHRI as the author?

Yes, we can use OHRI as the author: PHES-ODM@ohri.ca. 
@yulric, you can continue to be an author if you want.. I think it makes sense to have people's names, but I am totally fine if @zargot doesn't want to be named.

**Comment by yulric** [comment]
@zargot I believe I've removed your name from the commits and the file. Let me know if it all looks good.

**Review by zargot — APPROVED** [review]

**Pull request merged**
